# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 0
exemptLabels:
  - bug
  - enhancement
  - tech-debt
  - needs-design-input
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Thanks for your contribution!
   
  This issue has been automatically marked as stale because it has not had
  recent activity. Because the GitHub Desktop team treats their issues
  [as their backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), stale issues
  are closed. If you would like this issue to remain open:
   
   1. Verify that you can still reproduce the issue in the latest version of GitHub Desktop
   1. Comment that the issue is still reproducible and include:
      * What version of GitHub Desktop you reproduced the issue on
      * What OS and version you reproduced the issue on
      * What steps you followed to reproduce the issue
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
