osx_image: xcode8.3.3

dist: trusty
sudo: required

group: edge

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - libsecret-1-dev
      - rpm

language: c

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.0.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.0.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
  - nvm install 7
  - npm prune
  - cd app && npm prune && cd ..
  - npm install
  - npm ls --prod
  - npm ls --dev

script:
  - travis_wait 60 npm run release
  - npm run check-prettiness
  - npm run lint
  - npm run test:setup
  - npm test

after_failure:
  - npm run test:review
